#version: "3"
services:
  mysql:
    ports:
      - "3307:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "phpip"
    volumes:
      - dbData:/var/lib/mysql
      - ./script:/script
  php-apache:
    ports:
      - "81:80"
    build: './build/php'
    volumes:
      - ./app:/var/www/html
      - ./vendor:/var/www/phpip/vendor
volumes:
  dbData:
